apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    tier: prod
    app: front-end
spec:
  serviceAccountName: app-sa
  containers:
    - name: app-container
      image: nginx
      ports:
        - containerPort: 8080