apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: nginx-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      env:
        - name: NGNIX_PASSWORD
          value: amit

# env value is just learning not required
# kubectl create -f nginx-pod-defination.yml
# kubectl get pods
# kubectl describe pod nginx-pod