apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: nginx-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx

# kubectl create -f nginx-pod-defination.yml
# kubectl get pods
# kubectl describe pod nginx-pod