apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    tier: prod
    app: front-end
spec:
  containers:
    - name: app-container
      image: nginx
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config