apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: nginx-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      resources:
        limits:
          memory: 256Mi
        requests:
          memory: 100Mi