apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: nginx-app
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "app"
      operator: "equal"
      value: "BLUE"
      effect: "NoSchedule"


# Taint created via below command
# kubectl taint nodes nginx-node app:BLUE --NoSchedule